use customer_behavior;
select * from customer limit 20;
#q1 revenue generated by male vs female
select gender,sum(purchase_amount) as revenue from customer
group by gender;

#q2 which cudtomer used discount but still spent more than avg purchase amount
select customer_id,purchase_amount
from customer
where discount_applied="Yes" AND purchase_amount>=(select avg(purchase_amount) from customer);

#q3 which are top 5 products with highest average review rating
select item_purchased,round(avg(review_rating),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

#q4 compare avergae producr amounts between standard and express shipping
select shipping_type,
round(avg(purchase_amount),2) from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

#q5 do subscribed customers spend more?compare average spend and total revenue
-- between subscribers and non-subsribers
select subscription_status,count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status order by total_revenue,avg_spend desc;


